config/routes.rb
Rails.application.routes.draw do
  get 'author/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
  get "/books", to: "books#index", as: "books" #show all books
  post "/books", to: "books#create" #create a new books
  get "/books/new", to: "books#new", as: "new_book" #get a form
  get "/books/:id", to: "books#show", as: "book" #show a single book
  put "/books/:id", to: "books#update"
  patch "/books/:id", to: "books#update"
  get "/books/:id/edit", to: "books#edit", as: "edit_book" #get a form
  delete "/books/:id", to: "books#destroy"
   resources :authors
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
    validates :title, :author_id, :published_date, presence: true
    has_many :books_genres
    has_many :genres, through: :books_genres
end

app/models/books_genre.rb
class BooksGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books_genres
    has_many :books, through: :books_genres
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :find_book, only: [:show] 

  def index
    @authors = Author.all
  end

  def show

  end

  def new

  end

  def create
    @author = Author.create(author_params)
    #   name: params[:author][:name],
    #   date_of_birth: params[:author][:date_of_birth]
    # )
    redirect_to @author
  end

  def edit
     

  end

  def update

  end


  private
  def find_book
    @author = Author.find(params[:id])
  end

  def author_params 
      params.require(:author).permit(:name, :date_of_birth)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy] 
    def index
        # @books = session[:books]
        @books = Book.all
    end

    def create
      #    if session[:books] == nil
      #     session[:books] = []
      # end 

      # session[:books].push(params[:book])
      # redirect_to book_path(session[:books].length)
      
      # @book = Book.create(
      #   title: params[:book][:title],
      #   author: Author.find(params[:author_id]),
        
      #   published_date: params[:book][:published_date]
      # )
     
      @book = Book.create(book_params)
      # byebug

      # p "----------- @book"
      # p @book
      # p "-------@params"
      # p params
    
      redirect_to @book
    
    end
      
    def new
        
        @authors = Author.all
    end

    def show
        # @book_id = params[:id].to_i - 1
        # @book = session[:books][@book_id]

    end

    def edit
        # @book_id = params[:id].to_i - 1
        # @book = session[:books][@book_id]
        @authors = Author.all

    end


    def update
        # @book_id = params[:id].to_i - 1 
        # session[:books][@book_id] = params[:book]
        # redirect_to book_path(params[:id].to_i)
        # @book.update(book_params)
        # redirect_to @book
        # @book  =Book.find(params[:id].to_i)
        p "----------"
      #   pp @book
      #   @book.update(
      #   title: params[:book][:title],
      #   author: Author.find(params[:author_id]),
      #   # author: params[:author_id].to_i ,
      #   published_date: params[:book][:published_date]
      # )

      @book.update(book_params)
      p "-----"

      pp "@book=> ", @book
      
      redirect_to @book
    
        
    end

    def destroy
        @book.destroy
        redirect_to root_path
    end

    def find_book
        @book = Book.find(params[:id])
    end
    private

    def book_params 
      params.require(:book).permit( :title, :published_date, :author_id)
     
      
    end

   
end
     

      

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>



<div class="card-container">
    <% @authors.each do |author| %>
      <div class="card">
         <h3>Name: <%=  author.name  %> </h3>
         <h3>Date Of Birth: <%= author.date_of_birth %> </h3>
         
      
        <div class="links">
          <%= link_to "Update", edit_author_path(author.id) %>  
          <%= link_to "Show", author_path(author.id) %>
          <%= link_to "Delete", book_path(author.id), method: :delete, data: { confirm: "Are you sure?" } %>
          
        </div>
      </div>  
    <% end %>  
</div>
         
        

app/views/authors/new.html.erb
<h1>Add A New Author<h1>

<form action="<%= authors_path %>" method ="POST">

  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" /> 

    <label for="name">Name</label>
    <input type="text" name="author[name]" id="name"   />

    <label for="date_of_birth">Date Of Birth</label>
    <input type="date"  name="author[date_of_birth]" id="date_of_birth"   />
    <label for="author">Author</label>
    
   <input type="submit" value="Create An Author"/>

</form> 
    
    

    

    

app/views/authors/show.html.erb
<h3>Name: <%= @author.name %></h3>
<h3>Date Of Birth:<%= @author.date_of_birth %></h3>
<%= link_to "back", authors_path %>

app/views/books/edit.html.erb
<h1>Edit a book<h1>

<form action="<%= book_path(@book.id) %>" method="POST">

 <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" /> 


<input type="hidden" name="_method" value="patch" /> 

    <label for="title">Title</label>
    <input type="text" name="book[title]" id="title" value="<%= @book.title %>"   />

    <label for="author">Author</label>
    <input type="text"  name="book[author]" id="author" value="<%= @book.author.name %>"    />

    
    <select id="author" name="book[author_id]">
      <option>--Select Author--</option>
      <%@authors.each do | author | %>
        <option value=<%= author.id %>><%=author.name%></option> 
      <% end %>
    </select>

    <label for="date">Published date</label>
    <input type="date"   name="book[published_date]" id="date" value="<%= @book.published_date %>"  />


   <input type="submit" value="Update"/>

</form> 

app/views/books/index.html.erb
<h1>Book Page</h1>

<div class="card-container">
    <% @books.each do |book| %>
      <div class="card">
         <h3>Title: <%=  book.title  %> </h3>
         <h3>Author: <%= book.author.name %> </h3>
         <h3>Published date: <%= book.published_date %>   </h3>
      
        <div class="links">
         <%= link_to "Update", edit_book_path(book.id) %>
         <%= link_to "Show", book_path(book.id) %>
         <%= link_to "Delete", book_path(book.id), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>  
    <% end %>  
</div>

app/views/books/new.html.erb
<h1>Add A New Book<h1>

<form action="<%= books_path %>" method ="POST">

  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" /> 

    <label for="title">Title</label>
    <input type="text" name="book[title]" id="title"   /> 
<%# 
    <label for="author">Author</label>
    <input type="text"  name="book[author]" id="author"   /> %>
    <label for="author">Author</label>
    <select id="author" name="book[author_id]">
      <%@authors.each do | author | %>
        <option value=<%=  author.id %>><%=author.name%></option> 
      <% end %>
    </select>
    
    

    <label for="date">Published date</label>
    <input type="date" name="book[published_date]" id="date"   />

   <input type="submit" value="Create New Book"/>

</form> 
    



    

app/views/books/show.html.erb
<h3>Title: <%= @book.title %></h3>
<h3>Author:<%= @book.author.name %></h3>
<h3>Published date: <%=@book.published_date  %> </h3>
<%= link_to "back", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Library app</h1>

<h3><%= link_to "View All Books", books_path %> </h3>
<h3><%= link_to "Create A Book", new_book_path %> </h3>

<h3><%= link_to "View All Authors", authors_path %> </h3>

<h3><%= link_to "Create An Author", new_author_path %></h3> 